[versions]
java = "21"
spring-boot = "3.5.7"
spring-dependency-management = "1.1.7"
openapi-generator = "7.17.0"
openapi-tools = "0.2.8"
swagger = "2.2.40"
swagger-request-validator = "2.46.0"
jakarta-validation = "3.1.1"
lombok = "1.18.42"
commons-codec = "1.20.0"
find-bugs = "3.0.2"
gradle-nexus-publish-plugin = "2.0.0"
datadog-statsd = "4.4.5"
# Verify
checkstyle = "8.44"
pmd = "7.14.0"
jacoco = "0.8.13"
# Testing
mockito = "5.20.0"
junit-jupiter = "6.0.0"
junit-platform = "6.0.1"

[libraries]
openapi-tools-jacksonDatabindNullable = { group = "org.openapitools", name = "jackson-databind-nullable", version.ref = "openapi-tools" }
swagger-annotations = { group = "io.swagger.core.v3", name = "swagger-annotations", version.ref = "swagger" }
swagger-request-validator-core = { group = "com.atlassian.oai", name = "swagger-request-validator-core", version.ref = "swagger-request-validator" }
jakarta-validation-api = { group = "jakarta.validation", name = "jakarta.validation-api", version.ref = "jakarta-validation" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
datadog-statsdclient = { group = "com.datadoghq", name = "java-dogstatsd-client", version.ref = "datadog-statsd" }
commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commons-codec" }
find-bugs = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "find-bugs" }
# Testing
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform" }
javax-mail = { module = "com.sun.mail:javax.mail", version = "1.6.2" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradle-nexus-publish-plugin" }
